[workspace]
members = [
    "crates/*"
]

[workspace.package]
version = "0.0.1-alpha.1"
authors = ["Benedikt Schwab"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tum-gis/egml"

[workspace.dependencies]
thiserror = "1.0"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
nalgebra = "0.31.1"
serde = "1.0"
quick-xml = "0.27.0"
geo = "0.23.1"
