[package]
name = "egml-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI tool for GML operations"


[dependencies]
egml = { version = "0.0.1-alpha.1", path = "../egml", registry = "custom" }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
